language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mongodb
#before_script:
  - sleep 15
  - sudo service mongod status 
script:
  - python setup.py resizephotos
  - python -m unittest tests/test_*.py
