language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - mongodb
  - sleep 5
  - sudo service mongod status 
script:
  - python setup.py install
  - python -m unittest -v tests/test_*.py
